### ISSUE TITLE
possibility of use in prostate dataset

### ISSUE THREAD

**Issue by jakubMitura14** [neel-dey/Atlas-GAN#2]
Hello - Thanks for sharing your work !
I would like to use your algorithm on prostate dataset and  ask couple questions.
As far as I analyzed the code I do not see it taking into account spacing, orientation and direction - so I suppose all should be the same before starting training?

I have t2 weighted images in transverse, saggital and coronal plane and 3 resolutions for each 256x256; 512x512 and 1024x1024, should I train using all of the views of t2 or separately each? what do you think best do with differences in resolution - pad smaller images? resize and interpolate? train separate conditional template for each resolution?

I understand that some is unknown and possible to establish only by experimentation - but  you know your tool best so any comment would be highly valuable .

Thank you !

**Comment by neel-dey** [comment]
Hi @jakubMitura14,

Thanks for your interest! Yes, unfortunately, this repository does not account for physical metadata, so I would recommend standardization before processing (as you've already noted). Just FYI: I'm planning to improve this repo in early July after some thesis formalities are out of the way.

I'm unfamiliar with prostate imaging, could you clarify what you mean by:
```I have t2 weighted images in transverse, saggital and coronal plane and 3 resolutions for each 256x256; 512x512 and 1024x1024, should I train using all of the views of t2 or separately each?```

Are these multiple 2D slices of a 3D volume for each individual subject or does each subject have a single 2D image that could be axial/coronal/sagittal? Do the three planes have the same spacing? Do all images have roughly the same FOV for each plane?

If it's easier to just show the images and have a real time back-and-forth, I'm happy to hop on a zoom call or something after July 1st.

**Comment by jakubMitura14** [comment]
Fantastic! so now I will not take your time and get back after 1 July, keeping fingers crossed for PhD !

**Comment by neel-dey** [comment]
@jakubMitura14 I'm done with that now, feel free to email me at `neel DOT dey AT nyu DOT edu` and we can set up a call or something if you're still interested in using this framework :)
